version: "3.9"

services:

  server:
    container_name: news-server
    build: .
    ports:
      - 9090:9090
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: "production"
      PGUSER: "dentednerd"
      PGDATABASE: "nc_news"
      PGPASSWORD: "password"
      DATABASE_URL: "postgres://db:5432"

  db:
    container_name: postgres-db
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "dentednerd"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "nc_news"
      PGPASSWORD: "password"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
